services:
    db_test:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DATABASE__POSTGRES_PASSWORD}
            POSTGRES_DB: ${DATABASE__DB_NAME}
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
            interval: 1s
            timeout: 5s
            retries: 15
        ports:
            - '5433:5432'
